### ISSUE TITLE
Cannot find module yarn-3.3.0.cjs

### ISSUE THREAD

**Issue by braaar** [bjerkio/create-bjerk-typescript#185]
Something seems off with the configuration of yarn.

On a brand new project, this error occurs:
```
Error: Cannot find module '/Users/moripen/Documents/GitHub/abax-vwfs/.yarn/releases/yarn-3.3.0.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Module._load (node:internal/modules/cjs/loader:804:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by cobraz** [comment]
Hey!

I have set up a workflow that creates a new project, installs dependencies and runs tests and builds. This does not reproduce this error, however, so I'm not sure this is still valid?

Can you have a look here? https://github.com/bjerkio/create-bjerk-typescript/actions/runs/4025748801/jobs/6919370066

**Comment by cobraz** [comment]
Added installing a package (fastify in this case) to the mix to see if that changes anything. Unfortunately not.

https://github.com/bjerkio/create-bjerk-typescript/actions/runs/4025841241/jobs/6919581767

**Comment by cobraz** [comment]
I'm closing this now, let me know if it still happens!
